services:
  zstart_postgres:
    image: mooncakelabs/pg_mooncake:latest
    shm_size: 1g
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      DUCKDB_FORCE_EXECUTION: ${DUCKDB_FORCE_EXECUTION:-off}
    volumes:
      - zstart_pgdata:/var/lib/postgresql
      - ./init/01-setup-extensions.sql:/docker-entrypoint-initdb.d/01-setup-extensions.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
      - ./migrations/02_add_counter_quarters.sql:/docker-entrypoint-initdb.d/03-migration-counters.sql:ro
      - ./migrations/03_add_entities.sql:/docker-entrypoint-initdb.d/04-migration-entities.sql:ro
      - ./migrations/04_rollback_full_text_search.sql:/docker-entrypoint-initdb.d/05-migration-rollback.sql:ro
      - ./migrations/05_add_user_counters.sql:/docker-entrypoint-initdb.d/06-migration-user-counters.sql:ro
      - ./init/03-configure-duckdb.sql:/docker-entrypoint-initdb.d/07-configure-duckdb.sql:ro

volumes:
  zstart_pgdata:
    driver: local
